name: Android CI (Debug)

on:
  push:
    branches: [ "main", "workflowUpdate","remotellm"]
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Create local.properties with secrets
        run: |
          echo "sdk.dir=$ANDROID_HOME" >> local.properties

          # 添加你的 API 密钥
          echo "baidu.client_id=${{ secrets.BAIDU_CLIENT_ID }}" >> local.properties
          echo "baidu.client_secret=${{ secrets.BAIDU_CLIENT_SECRET }}" >> local.properties

        env:
          ANDROID_HOME: /usr/local/lib/android/sdk

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Show Gradle info
        run: ./gradlew -v

      - name: Run unit tests
        run: ./gradlew :app:testDebugUnitTest --no-daemon

      - name: Print success sentence if unit tests passed
        if: success()
        run: echo "all unit tests are passed"

      - name: Upload unit test results
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: app/build/test-results

#      - name: Start emulator and run instrumentation tests
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: 34
#          target: google_apis
#          arch: x86_64
#          force-avd-creation: true
#          profile: pixel_5
#          emulator-boot-timeout: 900
#          disable-animations: true
#          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-snapshot -no-boot-anim -camera-back none -camera-front none
#          script: ./gradlew :app:connectedDebugAndroidTest

      - name: Build Debug APK
        run: ./gradlew :app:assembleDebug

#      - name: Upload instrumentation test results
#        uses: actions/upload-artifact@v4
#        with:
#          name: instrumentation-test-results
#          path: app/build/outputs/androidTest-results/connected

      - name: Upload assets to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name}}
          files: |
            app/build/outputs/apk/debug/*.apk
            app/build/outputs/mapping/release/mapping.txt
